# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-project:
    name: Build Artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Extract GAV
      id: extract
      uses: andreacomo/maven-gav-extractor@v1
    - name: Log GAV
      run: |
        echo ${{ steps.extract.outputs.group-id }}
        echo ${{ steps.extract.outputs.artifact-id }}
        echo ${{ steps.extract.outputs.version }}
      shell: bash
    - name: ${{ steps.extract.outputs.artifact-id }}-${{ steps.extract.outputs.version }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.extract.outputs.artifact-id }}-${{ steps.extract.outputs.version }}
        path: /home/runner/work/hcl-accelerate-plugin/hcl-accelerate-plugin/target/hcl-accelerate.hpi

    - name: Download site content
      uses: actions/download-artifact@v2
      with:
        name: ${{ steps.extract.outputs.artifact-id }}-${{ steps.extract.outputs.version }}
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    - name: View content
      run: ls -R
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ${{ steps.extract.outputs.artifact-id }}-${{ steps.extract.outputs.version }}.hpi
        asset_name: ${{ steps.extract.outputs.artifact-id }}-${{ steps.extract.outputs.version }}.hpi
        asset_content_type: application/zip
